<a href="https://colab.research.google.com/github/MohylinaDiana/python_for_ds_tasks/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22hw_10_4_apply%2C_groupby%2C_pivot_table_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [ ]:
import pandas as pd
db = pd.read_csv("drive/MyDrive/supermarket_sales.csv")
df = pd.DataFrame(db)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [ ]:
branch_profit = df.groupby('Branch')['gross income'].sum()
most_profitable_branch = branch_profit.idxmax()
max_profit_value = branch_profit.max()

print("Сумарний прибуток по філіалах:")
print(branch_profit)

print(f"\nНайприбутковішим є філіал: {most_profitable_branch} з прибутком {max_profit_value}")

Сумарний прибуток по філіалах:
Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

Найприбутковішим є філіал: C з прибутком 5265.1765

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [ ]:
city_branch_profit = df.groupby(['City', 'Branch'])['gross income'].sum().reset_index()
city_branch_profit = city_branch_profit.sort_values(by='gross income', ascending=False)
top_city = city_branch_profit.iloc[0]['City']
top_profit = city_branch_profit.iloc[0]['gross income']

print(f"\nНайвищий прибуток має філіал у місті: {top_city} ({top_profit:.2f})")

Найвищий прибуток має філіал у місті: Naypyitaw (5265.18)

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [ ]:
invoices_by_category = df.pivot_table(index='Product line', columns='Branch', values='Invoice ID', aggfunc='count')

print(invoices_by_category)

Branch                   A   B   C
Product line
Electronic accessories  60  55  55
Fashion accessories     51  62  65
Food and beverages      58  50  66
Health and beauty       47  53  52
Home and lifestyle      65  50  45
Sports and travel       59  62  45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [ ]:
electronics_row = invoices_by_category.loc['Electronic accessories']
best_branch = electronics_row.idxmax()
max_invoices = electronics_row.max()

print(f"Найбільше інвойсів у категорії Electronic accessories у філіалі: {best_branch}")
print(f"Кількість покупок: {max_invoices}")

Найбільше інвойсів у категорії Electronic accessories у філіалі: A
Кількість покупок: 60

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

In [ ]:
#Чи справді Members витрачають більше грошей у середньому за один раз, ніж звичайні покупці?
df.groupby("Customer type")["Total"].mean()
#Учасники клубу витрачають трохи більше, але різниця невелика.
#Бізнес-рішення, якщо програма лояльності не дуже ефективна, то найкращий спосіб підвищити ії буде - додати більше акцій

Customer type
Member    327.791305
Normal    318.122856
Name: Total, dtype: float64

In [ ]:
#Які три категорії товарів приносять найбільший прибуток (gross income) для чоловіків, а які — для жінок?
df.groupby(["Gender", "Product line"])["gross income"] .sum().reset_index().sort_values(["Gender", "gross income"], ascending=[True, False]).groupby("Gender").head(3)
#Жінки більше купують - повсякденні та lifestyle-покупки
#Чоловіки - технології, догляд, і продукти зв'язанні зі спортом та активним відпочинком
#Бізнес-рішення - повсякденні та lifestyle-товари поставити біля входу, а технології, догляд, і продукти зв'язанні зі спортом та активним відпочинком у центральних проходах

    Gender            Product line  gross income
2   Female      Food and beverages     1579.5675
1   Female     Fashion accessories     1449.4000
4   Female      Home and lifestyle     1430.3275
9     Male       Health and beauty     1458.7025
6     Male  Electronic accessories     1296.9290
11    Male       Sports and travel     1264.1955

In [ ]:
#Чи впливає спосіб оплати на середній рейтинг магазину?
df.groupby("Payment")["Rating"].mean()
#Найвищий рейтинг має Credit card, але різниця мінімальна, проблем з оплатою немає

Payment
Cash           6.970058
Credit card    7.003215
Ewallet        6.947826
Name: Rating, dtype: float64